# Generated by Django 4.1.7 on 2023-02-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('appointments', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=100)),
            ],
        ),
    ]
